# Generated by Django 2.2.4 on 2019-09-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20190909_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='identificacion',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='permission_administrador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='permission_asistente',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='permission_colaborador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='permission_ponente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='tipo_idenficacion',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
