# Generated by Django 2.2 on 2019-09-30 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20190909_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo_evento', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('fecha_fin', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='permission_administrador',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='permission_asistente',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='permission_colaborador',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='permission_ponente',
        ),
        migrations.AlterField(
            model_name='profile',
            name='identificacion',
            field=models.IntegerField(default=0),
        ),
    ]
