# Generated by Django 2.2.7 on 2019-11-26 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_auto_20191126_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='estado_transaccion',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('proceso', 'En proceso')], default='proceso', max_length=10),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora',
            field=models.TimeField(default=datetime.time(10, 10, 49, 29461)),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='codigo_inscripcion',
            field=models.IntegerField(default=4754001),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo_transaccion',
            field=models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], default='compra', max_length=10),
        ),
    ]
