# Generated by Django 2.2 on 2019-09-30 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_actividad_ambiente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambiente',
            name='actividad',
        ),
        migrations.AddField(
            model_name='actividad',
            name='ambiente',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='eventos.Ambiente'),
            preserve_default=False,
        ),
    ]
