# Generated by Django 2.2 on 2019-09-30 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_auto_20190929_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('costo', models.FloatField(default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAsistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Preinscrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Paquete')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Paquete')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.CharField(blank=True, max_length=30)),
                ('motivo', models.CharField(max_length=100)),
                ('cantidad', models.FloatField(default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.CharField(max_length=30)),
                ('motivo', models.CharField(max_length=100)),
                ('cantidad', models.FloatField(default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=20)),
                ('nivel_categoria', models.IntegerField(default=1)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(blank=True)),
                ('tipoAsistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.TipoAsistencia')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='material',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eventos.Material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambiente',
            name='material',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eventos.Material'),
            preserve_default=False,
        ),
    ]
