# Generated by Django 2.2.7 on 2019-11-28 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_auto_20191126_1104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoAsistencia',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='tipo_asistencia',
            field=models.CharField(choices=[('general', 'General'), ('actividad', 'Actividad')], default='general', max_length=15),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora',
            field=models.TimeField(default=datetime.time(0, 15, 15, 188926)),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='codigo_inscripcion',
            field=models.IntegerField(default=4713545),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
