# Generated by Django 2.2.7 on 2019-11-28 05:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_auto_20191128_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='actividad',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.Actividad'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora',
            field=models.TimeField(default=datetime.time(0, 30, 36, 105423)),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='codigo_inscripcion',
            field=models.IntegerField(default=3532995),
        ),
    ]
