# Generated by Django 2.2 on 2019-09-30 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_auto_20190930_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='categoria_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eventos.CategoriaUsuario'),
        ),
    ]
