# Generated by Django 2.2 on 2019-10-02 20:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_auto_20191001_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='categoria_usuario',
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora',
            field=models.TimeField(default=datetime.time(15, 40, 53, 712816)),
        ),
        migrations.RenameModel(
            old_name='CategoriaUsuario',
            new_name='CategoriaPersonal',
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.CategoriaPersonal')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Profile')),
            ],
        ),
    ]
