# Generated by Django 2.2 on 2019-10-02 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0016_auto_20191002_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='hora',
            field=models.TimeField(default=datetime.time(15, 42, 31, 375745)),
        ),
    ]
