# Generated by Django 2.2 on 2019-10-02 20:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0017_auto_20191002_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriapersonal',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora',
            field=models.TimeField(default=datetime.time(15, 43, 20, 268231)),
        ),
    ]
