# Generated by Django 2.2 on 2019-10-05 18:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0018_auto_20191002_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expositor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('actividad', models.ManyToManyField(to='eventos.Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.CharField(max_length=30)),
                ('motivo', models.CharField(max_length=100)),
                ('cantidad', models.FloatField(default=0)),
                ('tipo_transaccion', models.CharField(max_length=15)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='preinscrito',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='preinscrito',
            name='paquete',
        ),
        migrations.RemoveField(
            model_name='preinscrito',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='tipoAsistencia',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='actividad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eventos.Actividad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asistencia',
            name='inscrito',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eventos.Inscrito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscrito',
            name='estado_inscripcion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialactividad',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='materialambiente',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paquete',
            name='actividad',
            field=models.ManyToManyField(to='eventos.Actividad'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora',
            field=models.TimeField(default=datetime.time(13, 25, 16, 736564)),
        ),
        migrations.RemoveField(
            model_name='categoriapersonal',
            name='evento',
        ),
        migrations.AddField(
            model_name='categoriapersonal',
            name='evento',
            field=models.ManyToManyField(to='eventos.Evento'),
        ),
        migrations.DeleteModel(
            name='Egreso',
        ),
        migrations.DeleteModel(
            name='Ingreso',
        ),
        migrations.DeleteModel(
            name='Preinscrito',
        ),
    ]
